name: SonarCloud analysis

on:
  push:
    branches:
      - main
      - module-2-exercise  # ✅ Tambahkan jika butuh analisis di branch lain
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read
  security-events: write  # ✅ Diperlukan untuk upload SARIF ke GitHub Security

jobs:
  build:
    name: Build and Analyze with SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # ✅ Penting agar SonarCloud bisa membaca riwayat commit

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'  # ✅ Pastikan sesuai dengan versi proyek

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Grant execute permissions for Gradle
        run: chmod +x gradlew  # ✅ Agar bisa berjalan di Linux

      - name: Build and analyze with SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew build sonar --stacktrace --info  # ✅ Perintah ini lebih optimal di Gradle

      - name: Upload SARIF to GitHub Security
        if: success()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
